### ISSUE TITLE
name_monoid.show_name setting has no effect

### ISSUE THREAD

**Issue by insanity54** [fluxionary/minetest-name_monoid#1]
Thank you for this mod!

When I put `name_monoid.show_name = false` in my minetest.conf file, players still get nametags when they join.

I think the problem lies in how the register_on_joinplayer function does the hiding. I don't think it's effective and I'm not sure why.

https://github.com/fluxionary/minetest-name_monoid/blob/1586b3b4c8e09d15d71e72652c73b3a69aee4608/init.lua#L32

When I replaced that code with the following, I got the hidden nametag effect I was looking for.
```lua
nametag_attributes = {
  hide_all = true
}
name_monoid.monoid:add_change(player, nametag_attributes, "name_monoid")
```

**Comment by fluxionary** [comment]
sorry i haven't replied earlier, i'll take a look

**Comment by fluxionary** [comment]
turns out that setting the "text" of a nametag to the empty string has the effect of making it display the default value - the player's name. the solution is apparently to hide it via setting the alpha channel to 0. should now be fixed w/ the latest commit, care to test it?

**Comment by fluxionary** [comment]
closing as "it works for me", reopen if it's still broken.
