### ISSUE TITLE
settingstypes.txt is missing

### ISSUE THREAD

**Issue by insanity54** [fluxionary/minetest-name_monoid#2]
Thank you for this mod! I've found it useful. One thing I thought was helpful was to have a settingstypes.txt file so I could make changes to the config while testing. In case it's helpful to you, here is what I came up with.

```txt
# Whether or not to show player names above their head when they join
# Set to true to show names, false to hide names
name_monoid.show_name (Show Names) bool true

# Tag separator used to separate components in the name tag
name_monoid.tag_separator (Tag Separator) string " "

# Invert composition determines the order of components in the name tag
# Set to true to invert the order, false to keep the order as defined
name_monoid.invert_composition (Invert Composition) bool false
```

**Comment by fluxionary** [comment]
there's already a settingstype.txt file isn't there? https://github.com/fluxionary/minetest-name_monoid/blob/main/settingtypes.txt

but your descriptions are much better, i'll adopt those and give you credits.

**Comment by fluxionary** [comment]
done
