### ISSUE TITLE
No way to have a space character as tag_separator

### ISSUE THREAD

**Issue by Bastrabun** [fluxionary/minetest-name_monoid#3]
settingttypes of name_monoid now have a default value:

```
# tag separator used to separate components in the name tag
name_monoid.tag_separator (tag separator) string " "
```

Together with the party mod, this causes the tag_separator display a `"` character.

I can remove the tag separator entirely by leaving the setting empty:

```
name_monoid.tag_separator = 
```

Please add a way to have a single blank/spacebar character between partytag and playername

For my reference 5301

**Comment by fluxionary** [comment]
oh right, this bug. this might actually be a bug in how fmod reads default values, will take a look.

**Comment by fluxionary** [comment]
fixed the issue in fmod https://github.com/fluxionary/minetest-fmod/commit/1029b7224b342f72dac3af1e1009c76db25d087e
